### ISSUE TITLE
iOS客户端发着查询无法正常工作

### ISSUE THREAD

**Issue by wangyk55** [Arnie97/moerail#12]
机型：iPhone Xs max
系统：16.3.1
描述：在客户端内搜索站名无显示且无法选择车站，但车组/车次查询可以正常工作。（客户端默认填入的北京至上海的查询可以正常进行）![image](https://github.com/Arnie97/moerail/assets/58785348/9fbde952-feca-4ad9-b217-a29ccf7a442c)

**Comment by Arnie97** [comment]
@hqy2000 帮忙看看。

另外我给你开了此仓库的写权限，如果你喜欢可以把 issue 移动到 EMURoutingTracker。当然放在我这里也 OK

**Comment by wangyk55** [comment]
> @hqy2000 帮忙看看。
> 
> 
> 
> 另外我给你开了此仓库的写权限，如果你喜欢可以把 issue 移动到 EMURoutingTracker。当然放在我这里也 OK

刚才又尝试了一下，车站选择可以正常工作了。。。

另外广珠城际的部分列车好像是有信息缺失吗？搜索广州->珠海能够搜索到C7601、C7603等车次，但是反过来搜索珠海->广州就搜不到C7602、C7604等对开车次（搜索途径站小榄->广州反而能搜到C7602、C7604），不知道是数据源的原因还是什么呢？

我对iOS开发不是很在行，但也尝试着看一下

**Comment by hqy2000** [comment]
我周末来研究一下。但这个 app 肯定过不了 ICP 备案，估计也存活不了多久了。

**Comment by hqy2000** [comment]
问题修复了，之前改了域名但忘记去 App Store 更新版本
