### ISSUE TITLE
火车票二维码解读

### ISSUE THREAD

**Issue by yzj17** [Arnie97/moerail#14]
您好
从您的软件上看到有扫码查询功能，可以扫码查出火车票的所有信息。所以想请教一下编码的规则。虽然看到了您发布了代码，但我没有学习过这方面知识，所以还是需要请教一下。

**Comment by Arnie97** [comment]
这是前铁道部设计二维码时候的七年虫问题，无解。点年份的位置可以旋转到下一个年份
