### ISSUE TITLE
近日中国铁路调图，贵产品的交路图是否有更新的计划？

### ISSUE THREAD

**Issue by C10H** [Arnie97/moerail#17]
我认为这可能是一项庞大的工程，但是贵号的D9次列车的交路图仍然是调图前，北京到沈阳北的CRH5E时期的交路图。
![image](https://github.com/Arnie97/moerail/assets/64535522/4560d00d-b15c-4129-bf9c-7063076970ee)

**Comment by C10H** [comment]
工程量太大的话就算了

**Comment by Arnie97** [comment]
其实不是今年没更新，是五年没更新过了（小声

建议您点击第一列「车组号」来跟踪最新的交路信息，图片仅作为历史遗迹保留，没有太大价值了

**Comment by Arnie97** [comment]
已在网站更新历史中补充相关说明，感谢您的建议。
