### ISSUE TITLE
搜索问题

### ISSUE THREAD

**Issue by YYLWZDXPGD** [Arnie97/moerail#18]
最近开通了一些车站，如广州白云站等，未显示在车站搜索
![IMG_5662](https://github.com/Arnie97/moerail/assets/128379352/6caedee7-32f1-4aec-a8ea-83bac9123008)
Z、T、K等普速列车也没有搜索出来
![IMG_5663](https://github.com/Arnie97/moerail/assets/128379352/7af4ff41-3ccd-47a8-8246-27a06e775340)
K1804是真实车次，为湛江-武昌

**Comment by Arnie97** [comment]
感谢您的建议。最近开通的车站未在搜索中显示，是因为 2023-03-07 后没有更新过车站数据。<del>一年不开张，开张吃一年，应该快更新了，咕咕咕</del>

由于缺乏相关数据源支持，本站从未展示过非动车组列车的担当和交路。
