### ISSUE TITLE
Appstore好像国区和美区都无法下载软件了，希望开发者解决一下

### ISSUE THREAD

**Issue by Hanson-hzc** [Arnie97/moerail#19]
如题，望解决

**Comment by Arnie97** [comment]
您好，看起来和 https://github.com/hqy2000/EMURoutingTracker/issues/5 报告的是同一个问题。我这边解决不了，我们等 iOS 端的作者回复吧。

**Comment by hqy2000** [comment]
抱歉，因为 Apple Developer 自动续费没有成功被下架了，现在已经恢复了
