### ISSUE TITLE
查车次查车号又显示加载失败

### ISSUE THREAD

**Issue by bmybgm** [Arnie97/moerail#26]
是不是最近放暑假导致访问量过大进而导致服务器负载吃不消？

**Comment by Zheng-Yitong** [comment]
我在7月5日使用江苏电信移动数据，遇到了同样的问题：网页端加载失败，APP端的「余票查询」页面无法正常加载，「车次查询」页面无法加载出当日及历史担当车次。
但是在7月8日夜间，我再次使用网页端及APP，功能均已经恢复正常，使用安徽电信固定宽带及移动数据均测试。希望可以提供帮助。
