### ISSUE TITLE
app 和网页端显示加载失败

### ISSUE THREAD

**Issue by zhangyichen2006** [Arnie97/moerail#27]
app
和网页端显示加载失败
![image](https://github.com/Arnie97/moerail/assets/104629701/d759bc05-136b-4541-8872-9d39eef182ff)

**Comment by Zheng-Yitong** [comment]
我在7月5日使用江苏电信移动数据，遇到了同样的问题：网页端加载失败，APP端的「余票查询」页面无法正常加载，「车次查询」页面无法加载出当日及历史担当车次。
但是在7月8日夜间，我再次使用网页端及APP，功能均已经恢复正常，使用安徽电信固定宽带及移动数据均测试。希望可以提供帮助。
