### ISSUE TITLE
能不能追加一个目击上传？

### ISSUE THREAD

**Issue by njfdCRH1A** [Arnie97/moerail#4]
因为部分路局的动车组信息无法查询所以能不能追加一个目击上传功能？
另外好像是通过点餐二维码实现的然后南局没这玩意……

**Comment by Arnie97** [comment]
> 因为部分路局的动车组信息无法查询所以能不能追加一个目击上传功能？

管理难度太大了，没法阻止传入错误信息


> 另外好像是通过点餐二维码实现的然后南局没这玩意…

南局的可能现在已经撕光了，因为那个系统看起来已经不能用了。如果你看到旁边带京东金融字样的点餐码，大概率属于这个系统，别的系统一般仅支持微信扫码登录（或微信+支付宝）。一个（我自己虚构的）南局点餐码以及这个码当年产生的结果：

https://p.12306.cn/tservice/catering/init?c=GCRH380A250108008Ah&w=h
https://moerail.ml/#380A2501

其实南局我有别的路子能查到，但是依赖「哪些开行车次现在是南局车底担当的」这项基础数据。
如果您有空闲时间的话可以协助整理，否则要等我设法解析某时刻表提供的担当局数据，可能短时间内没空做。

**Comment by njfdCRH1A** [comment]
12306貌似最近出另外一种码了（见https://mp.weixin.qq.com/s?__biz=MzA3NzAyMzMyMA==&mid=2247486277&idx=1&sn=bd71f1e14bd3472bf25f46fb4cf8e9ae&chksm=9f591a72a82e9364cb242ad46825f321f3a70fb1aea911845ee3e869f268e42dd2e9e4b324c7&mpshare=1&scene=23&srcid=0728eAehDTIXWfZK59Auqb6n&sharer_sharetime=1658969197202&sharer_shareid=77a69887ecc3c53a7b6927aa599a564f#rd）
文章中的码可以直接扫（CR400AF-Z-0216）通过强行改列车号的方法，目前试出来可能只有部分路局部分列车能用（测试列车分别为CRH1A-1001（广），CRH2A-2001（上），CR400AF-A-1001（广），CR400BF-5033（京），CR400AF-2222（上），CRH380AL-2541（京），CRH2A-2828（济）；其中CRH1A-1001，CRH2A-2001，CR400AF-2222，CRH380AL-2541显示功能未开通，CR400AF-A-1001显示当前车次为G1189；CR400BF-5033显示当前车次为G292，CRH2A-2828显示当前车次为D1638/D1635）

**Comment by njfdCRH1A** [comment]
目前试出来的结果
南局的试了CRH1A-1111、CRH2A-2222、CRH380A-2501、CRH1A-A-1186、CR200J-6020均不行
武局的智动均可（文章示例即为武局的CR400AF-Z-0216）但是好像也就只有智动可以……
广铁可能只有复兴号动分可以
兰局丢了CR300BF-3011进去直接告诉我操作失败
西局可能都不能用
成局也可能都不能用

**Comment by Arnie97** [comment]
武局每天都在新贴，现在几乎全局都可以了。广铁成局正在从旧二维码缓慢过渡。

**Comment by shaotong2003** [comment]
为什么有的车子又查不到了

**Comment by shaotong2003** [comment]
上局的bfbz 5208又查不到了还有af 2225 af 2232都查不到了

**Comment by Arnie97** [comment]
BF-BZ-5208 应当是撕掉了原先华东印记的点餐码，换成了铁路畅行的，我今天手动做了调整。但是上局不像京局直接一次性关掉了整个旧的系统，有很多车现在新旧两种都有（例如 BF-BZ-5209），有些车目前还只贴了旧版的，在全部更换完前很难处理。

**Comment by njfdCRH1A** [comment]
南局的可能有戏https://mp.weixin.qq.com/s?__biz=MjM5NTYwMTc0MA==&mid=2651905369&idx=1&sn=52f54ba65552c9cc2cc2c79781d8817f&chksm=bd12717a8a65f86c4a46189ee44b7141c5c25132c9af0bf577290892ed859bd20ba43e4a3514&mpshare=1&scene=23&srcid=0826RXrVvougLzddC3pgTEO6&sharer_sharetime=1661513104960&sharer_shareid=77a69887ecc3c53a7b6927aa599a564f#rd

**Comment by Arnie97** [comment]
可，我找南昌西一所二所的人问问

**Comment by shaotong2003** [comment]
我现在有BF-BZ 5208的码了，现在是否需要

**Comment by Arnie97** [comment]
我有几千个 5208 的码，现在的问题其实不是没有码。

**Comment by Arnie97** [comment]
@njfdCRH1A 目前已经能查到南局 70 多组 380A(L)，包括 [6001](https://moerail.ml/#2501)。看起来南局 1A(-A) 和 2A 并未接入。

**Comment by njfdCRH1A** [comment]
> @njfdCRH1A 目前已经能查到南局 70 多组 380A(L)，包括 [6001](https://moerail.ml/#2501)。看起来南局 1A(-A) 和 2A 并未接入。

可能目前只有南局的CRH380A(L)贴了
可能要380A的贴完再贴1A/1A-A/2A的

**Comment by njfdCRH1A** [comment]
南局的对应好乱，一下子看不出来是什么规律
G0016174对应CRH380A-2784-04-08C
G0026174对应CRH380AL-2563-15-09D
G0026175对应CRH380AL-2563-15-09F
G0056174对应CRH380A-2886-05-12A
G0055974对应CRH380A-2886-03-14A
G0055674对应CRH380A-2817-06-10D
G0055074对应CRH380A-2683-06-01F
G0146174对应CRH380A-2531-01-10F

**Comment by njfdCRH1A** [comment]
对了还有安卓端应用能不能优化一下……相比IOS端安卓端的使用体验实在是不好，并且安卓端的功能少好多（比如说二维码上传功能）

**Comment by Arnie97** [comment]
@njfdCRH1A [iOS 端](https://github.com/hqy2000/ChinaEMU)是专业 iOS 开发者 @hqy2000 的作品，是一个从零搭建出来的独立应用，交互合理，功能完整。

我自己也是 Android 用户，没有 iOS 设备，但我不是 Android 开发者，也没有时间和计划系统的学习 Android。[目前我基于 12306 的网页随便糊的这个 Android 端](https://github.com/Arnie97/webview-inject/blob/master/app/src/main/java/ml/moerail/MainActivity.java#L38)，只能算聊胜于无，把[浏览器扩展](https://github.com/Arnie97/moerail-tools/blob/master/emu.user.js)原样搬到了移动端。招募 Android 开发者 :-)
