### ISSUE TITLE
关于自动更新慢的问题

### ISSUE THREAD

**Issue by njfdCRH1A** [Arnie97/moerail#7]
畅行码已经可以扫出来信息了但是这边还是查不到，要再手动上次一次畅行码才会刷新

**Comment by Arnie97** [comment]
抱歉，我没有听懂问题描述
1）前半句，扫出来是指微信扫出来了，还是指用动车组交路查询 iOS 客户端扫出来了
2）后半句，做了怎么样的操作后能手动刷新？

**Comment by Arnie97** [comment]
这个现象是符合预期的啊。用微信或者支付宝扫，我这边完全不会知道有这个点餐码。

我不定期人工浏览用户在我站上传的实际点餐码，来推测和修订生成其他点餐码的规则。如果我写的规则和用户上传的点餐码都没有覆盖到某一辆车，那在我这里就查不到

**Comment by Arnie97** [comment]
这个现象是符合预期的。现在设定的爬取速度较慢，循环一遍所有车底所需的时间较长。
而主动扫描二维码，会立即触发对一辆车的爬取

**Comment by Arnie97** [comment]
这个现象是符合预期的。
现在我设定爬取速度的标准是，在避免遗漏短途车次的前提下，越慢越好，因此循环一遍所有车底所需的时间较长。
而主动扫描二维码，会立即触发对一辆车底的爬取

**Comment by Arnie97** [comment]
这个现象是符合预期的。
现在我设定爬取速度的标准是，在避免遗漏短途车次的前提下，越慢越好，因此循环一遍所有车底所需的时间较长。
而主动扫描二维码，会立即请求 12306 进行查询和记录

**Comment by Arnie97** [comment]
@njfdCRH1A 请问 895 结尾的数十个点餐码是你提交的吗。
请不要提交没有实际贴在车上，只是根据编号规则推测出的点餐码，即便推测结果能扫出来车次信息。
系统本身拥有按编号规则生成点餐码的功能，扫码主要是为了协助我发现新的点餐平台和编号方式。大量提交相同模式的点餐码没有意义，只会增加人工浏览审核的工作量。
