### ISSUE TITLE
网站貌似无法访问了

### ISSUE THREAD

**Issue by Georgebillion** [Arnie97/moerail#9]
rt，我7.20晚上上的时候直接没办法查交路，然后是整个网址都上不去了

**Comment by Arnie97** [comment]
目前域名解析发生故障，正在与域名注册商接洽。近期可以用备用域名 https://moerail.mirrors.tk 访问

**Comment by Georgebillion** [comment]
有无预计恢复时间？

**Comment by Arnie97** [comment]
> 有无预计恢复时间？

目前假设域名永久无法恢复，在准备后续迁移工作：[moerail.ml 新域名调查问卷](https://test-c6xkh397ejfy.feishu.cn/share/base/form/shrcn2SaPvg2bE3djzt9NeMWisc)

**Comment by EndstoneV** [comment]
我用中国移动流量可以打开
